blender_version_min = "4.2.0"
id = "KengoHoi_OpenTextFile"
license = ["SPDX:MIT"]
maintainer = "Kengo Hoi <kengohoi1027@gmail.com>"
name = "OpenTextFile"
schema_version = "1.0.0"
tagline = "Add a text object of URL from the clipboard. And, open the URL of a text object."
type = "add-on"
version = "1.0.0"
website = "https://github.com/kengo6053/OpenTextFile"
